name: Build and Test Packages
on: [ push ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3
        with:
          cmd: install
      - uses: borales/actions-yarn@v3
        with:
          cmd: test:unit
